# Generated by Django 4.1.2 on 2022-11-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_shopvegedb_delete_shopvegdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shopvegedb',
            new_name='shopvegdb',
        ),
    ]
