# Generated by Django 4.1.2 on 2022-11-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_productdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Quantity',
        ),
    ]
