# Generated by Django 4.1.2 on 2022-11-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_productdb_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category',
            new_name='CategoryName',
        ),
    ]
